name: eduquest

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  http: ^1.2.2
  file_selector: ^1.0.3
  cupertino_icons: ^1.0.6
  flutter_pdfview: ^1.3.2
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.1
  animated_splash_screen: ^1.3.0
  provider: ^6.0.1
  path_provider: ^2.0.11
  pdfx: ^2.8.0
  syncfusion_flutter_pdf: ^26.2.7
  image_picker: ^1.1.2
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  image_cropper: ^8.0.2
  cloud_functions: ^5.1.3
  email_validator: ^3.0.0
  fluttertoast: ^8.2.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img.png"

flutter:
  uses-material-design: true

  assets:
    - .env
